### ISSUE TITLE
Please remove user "typo3" as maintainer of typo3-ter/* packages on packagist

### ISSUE THREAD

**Issue by helhum** [lars85/TYPO3-Extensions-lp_access#2]
The official "typo3" user should only be maintainer of official TYPO3 products.

See, e.g.: https://packagist.org/packages/typo3-ter/lp-access

**Comment by lars85** [comment]
see

*Add "typo3" as additional maintainer of your package on Packagist. This is
required to have Gerrit's hook correctly triggering the update on
Packagist.*

at

*http://composer.typo3.org/ <http://composer.typo3.org/>*

**Comment by lars85** [comment]
see
    Add "typo3" as additional maintainer of your package on Packagist. This is required to have Gerrit's hook correctly triggering the update on Packagist.
at
    http://composer.typo3.org/

Is the description on composer.typo3.org not correct?

**Comment by helhum** [comment]
Oh, well. I disagree with this practice and obviously didn't know about it.

I consider publishing TYPO3 extensions as packages on packagist a bad thing on its own, but requiring typo3 user to be added as maintainer is a very ugly and misleading hack to make something work.

But yes, should be discussed otherwise

**Comment by helhum** [comment]
But in your case: you're not hosting the git repo on git.typo3.org (see section * if you are hosting your code on git.typo3.org*), thus you can safely add your own packagist integration here on github as you neither benefit from having the typo3 user as maintainer, nor it is required by any means.

**Comment by lars85** [comment]
yep, thats right @helhum, thanks.. I have removed typo3 as maintainer..

**Comment by helhum** [comment]
Thanks a bunch!
